//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexxtVoucher.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anular.
        /// </summary>
        public static string ButtonAnular {
            get {
                return ResourceManager.GetString("ButtonAnular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        public static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectar.
        /// </summary>
        public static string ButtonConnect {
            get {
                return ResourceManager.GetString("ButtonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ButtonDetail {
            get {
                return ResourceManager.GetString("ButtonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Excel.
        /// </summary>
        public static string ButtonExcel {
            get {
                return ResourceManager.GetString("ButtonExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string ButtonList {
            get {
                return ResourceManager.GetString("ButtonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        public static string ButtonReport {
            get {
                return ResourceManager.GetString("ButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Cachier_Model_Activo {
            get {
                return ResourceManager.GetString("Cachier_Model_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Cachier_Model_Address {
            get {
                return ResourceManager.GetString("Cachier_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string Cachier_Model_City {
            get {
                return ResourceManager.GetString("Cachier_Model_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campañia.
        /// </summary>
        public static string Cachier_Model_Company {
            get {
                return ResourceManager.GetString("Cachier_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Cachier_Model_DocuType {
            get {
                return ResourceManager.GetString("Cachier_Model_DocuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Cachier_Model_Email {
            get {
                return ResourceManager.GetString("Cachier_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Cachier_Model_FirstName {
            get {
                return ResourceManager.GetString("Cachier_Model_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Cachier_Model_FullName {
            get {
                return ResourceManager.GetString("Cachier_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Indentidad.
        /// </summary>
        public static string Cachier_Model_Identification {
            get {
                return ResourceManager.GetString("Cachier_Model_Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Cachier_Model_LastName {
            get {
                return ResourceManager.GetString("Cachier_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Cachier_Model_Movil {
            get {
                return ResourceManager.GetString("Cachier_Model_Movil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Servidor.
        /// </summary>
        public static string Cachier_Model_MultiServer {
            get {
                return ResourceManager.GetString("Cachier_Model_MultiServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Cachier_Model_Phone {
            get {
                return ResourceManager.GetString("Cachier_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Cachier_Model_Zona {
            get {
                return ResourceManager.GetString("Cachier_Model_Zona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajeros.
        /// </summary>
        public static string Cachier_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Cachier_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo Encriptado.
        /// </summary>
        public static string ChainCode_Intext_Titulo {
            get {
                return ResourceManager.GetString("ChainCode_Intext_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encriptado.
        /// </summary>
        public static string ChainCode_Model_Cadena {
            get {
                return ResourceManager.GetString("ChainCode_Model_Cadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteres.
        /// </summary>
        public static string ChainCode_Model_Largo {
            get {
                return ResourceManager.GetString("ChainCode_Model_Largo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string City_Model_City {
            get {
                return ResourceManager.GetString("City_Model_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string City_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("City_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Seleccionar...].
        /// </summary>
        public static string ComboSelect {
            get {
                return ResourceManager.GetString("ComboSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Company_Model_Active {
            get {
                return ResourceManager.GetString("Company_Model_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Company_Model_Address {
            get {
                return ResourceManager.GetString("Company_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        public static string Company_Model_Anulado {
            get {
                return ResourceManager.GetString("Company_Model_Anulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_Model_Compania {
            get {
                return ResourceManager.GetString("Company_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Company_Model_Country {
            get {
                return ResourceManager.GetString("Company_Model_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string Company_Model_Desde {
            get {
                return ResourceManager.GetString("Company_Model_Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string Company_Model_Hasta {
            get {
                return ResourceManager.GetString("Company_Model_Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Company_Model_Logo {
            get {
                return ResourceManager.GetString("Company_Model_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Company_Model_Phone {
            get {
                return ResourceManager.GetString("Company_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nit / CI.
        /// </summary>
        public static string Company_Model_Rif {
            get {
                return ResourceManager.GetString("Company_Model_Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software PC.
        /// </summary>
        public static string Company_Model_SoftwarePC {
            get {
                return ResourceManager.GetString("Company_Model_SoftwarePC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Company_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar Excel.
        /// </summary>
        public static string ExportExcel_Titulo {
            get {
                return ResourceManager.GetString("ExportExcel_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket WIFI Mikrotik.
        /// </summary>
        public static string HomeIndex_Titulo1 {
            get {
                return ResourceManager.GetString("HomeIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccion Multiples Servidores.
        /// </summary>
        public static string HomeIndex_Titulo2 {
            get {
                return ResourceManager.GetString("HomeIndex_Titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta por Cajero.
        /// </summary>
        public static string HomeIndex_Titulo3 {
            get {
                return ResourceManager.GetString("HomeIndex_Titulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string Identification_Model_TipoDocumento {
            get {
                return ResourceManager.GetString("Identification_Model_TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string Identification_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Identification_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrotik.
        /// </summary>
        public static string Link1 {
            get {
                return ResourceManager.GetString("Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrotik PC.
        /// </summary>
        public static string Link11 {
            get {
                return ResourceManager.GetString("Link11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiples Servidores Mikrotik de Ticket para redes LAN y Tickes disponibles en la Web..
        /// </summary>
        public static string Link11Text {
            get {
                return ResourceManager.GetString("Link11Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maneja Multiples Servidores Mikrotik.  Servicios de Creacion de Ticket para redes Privadas y Manejo Individual si cuenta con IP Publicas..
        /// </summary>
        public static string Link1Text {
            get {
                return ResourceManager.GetString("Link1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes.
        /// </summary>
        public static string Link2 {
            get {
                return ResourceManager.GetString("Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibilidad.
        /// </summary>
        public static string Link21 {
            get {
                return ResourceManager.GetString("Link21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sistema Web y Sistema PC cuenta con la compatibilidad de los Firmware 6.43 o superior de Mikrotik..
        /// </summary>
        public static string Link21Text {
            get {
                return ResourceManager.GetString("Link21Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes crear Planes diferentes para cada servidor registrado en el software.  Organizarlos por Categorias que definen cada Servidor. .
        /// </summary>
        public static string Link2Text {
            get {
                return ResourceManager.GetString("Link2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Link3 {
            get {
                return ResourceManager.GetString("Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soporte.
        /// </summary>
        public static string Link31 {
            get {
                return ResourceManager.GetString("Link31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soporte WhatApps o Remoto por AnyDesk, Video Tutorial disponible para manejar el Software..
        /// </summary>
        public static string Link31Text {
            get {
                return ResourceManager.GetString("Link31Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea Pool de Ticket en un solo acceso y crea cajeros para vendan estos tickets.  Los cajeros solo venderan los tickets que el sistema tiene disponibles..
        /// </summary>
        public static string Link3Text {
            get {
                return ResourceManager.GetString("Link3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} debe ser menor de {1} characters.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nosotros.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de Acceso.
        /// </summary>
        public static string MenuAcceso {
            get {
                return ResourceManager.GetString("MenuAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string MenuAdministrador {
            get {
                return ResourceManager.GetString("MenuAdministrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string MenuAdministrador_Company {
            get {
                return ResourceManager.GetString("MenuAdministrador_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string MenuAdministrador_User {
            get {
                return ResourceManager.GetString("MenuAdministrador_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo.
        /// </summary>
        public static string MenuArchivo_Archivo {
            get {
                return ResourceManager.GetString("MenuArchivo_Archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Planes.
        /// </summary>
        public static string MenuArchivo_CategoriaPlan {
            get {
                return ResourceManager.GetString("MenuArchivo_CategoriaPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        public static string MenuArchivo_Ciudad {
            get {
                return ResourceManager.GetString("MenuArchivo_Ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string MenuArchivo_Plan {
            get {
                return ResourceManager.GetString("MenuArchivo_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidores.
        /// </summary>
        public static string MenuArchivo_Servidores {
            get {
                return ResourceManager.GetString("MenuArchivo_Servidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string MenuArchivo_Zona {
            get {
                return ResourceManager.GetString("MenuArchivo_Zona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos.
        /// </summary>
        public static string MenuData_Data {
            get {
                return ResourceManager.GetString("MenuData_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad Bajada.
        /// </summary>
        public static string MenuData_Download {
            get {
                return ResourceManager.GetString("MenuData_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Inactivo.
        /// </summary>
        public static string MenuData_TiempoInactivo {
            get {
                return ResourceManager.GetString("MenuData_TiempoInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Refrescar.
        /// </summary>
        public static string MenuData_TiempoRefrescar {
            get {
                return ResourceManager.GetString("MenuData_TiempoRefrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Ticket.
        /// </summary>
        public static string MenuData_TiempoTicket {
            get {
                return ResourceManager.GetString("MenuData_TiempoTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad Subida.
        /// </summary>
        public static string MenuData_Upload {
            get {
                return ResourceManager.GetString("MenuData_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Usuario.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despacho Ticket.
        /// </summary>
        public static string MenuOperacion_DespachoTicket {
            get {
                return ResourceManager.GetString("MenuOperacion_DespachoTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tickets.
        /// </summary>
        public static string MenuOperation_CrearTicket {
            get {
                return ResourceManager.GetString("MenuOperation_CrearTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciones.
        /// </summary>
        public static string MenuOperation_Operation {
            get {
                return ResourceManager.GetString("MenuOperation_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Ticket.
        /// </summary>
        public static string MenuOperation_VentaTicket {
            get {
                return ResourceManager.GetString("MenuOperation_VentaTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Cajero.
        /// </summary>
        public static string MenuOperation_VentaTicketCajero {
            get {
                return ResourceManager.GetString("MenuOperation_VentaTicketCajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        public static string MenuReport_Reportes {
            get {
                return ResourceManager.GetString("MenuReport_Reportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket por Cajero.
        /// </summary>
        public static string MenuReport_TicketCajero {
            get {
                return ResourceManager.GetString("MenuReport_TicketCajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajeros.
        /// </summary>
        public static string MenuSystem_Cajeros {
            get {
                return ResourceManager.GetString("MenuSystem_Cajeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadena Encriptado.
        /// </summary>
        public static string MenuSystem_ChainCode {
            get {
                return ResourceManager.GetString("MenuSystem_ChainCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo.
        /// </summary>
        public static string MenuSystem_Consecutivo {
            get {
                return ResourceManager.GetString("MenuSystem_Consecutivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string MenuSystem_DocumentType {
            get {
                return ResourceManager.GetString("MenuSystem_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string MenuSystem_Impuesto {
            get {
                return ResourceManager.GetString("MenuSystem_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string MenuSystem_System {
            get {
                return ResourceManager.GetString("MenuSystem_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string MenuSystem_TextoEncabezado {
            get {
                return ResourceManager.GetString("MenuSystem_TextoEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte por Tickets.
        /// </summary>
        public static string MenuSystem_TicketsReport {
            get {
                return ResourceManager.GetString("MenuSystem_TicketsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Vendidos.
        /// </summary>
        public static string MenuSystem_TicketsVendidos {
            get {
                return ResourceManager.GetString("MenuSystem_TicketsVendidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexion Mikrotik.
        /// </summary>
        public static string MikrotikConnection {
            get {
                return ResourceManager.GetString("MikrotikConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexion Fallida.
        /// </summary>
        public static string MikrotikFailed {
            get {
                return ResourceManager.GetString("MikrotikFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexion Exitosa.
        /// </summary>
        public static string MikrotikSuccess {
            get {
                return ResourceManager.GetString("MikrotikSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donwload.
        /// </summary>
        public static string Model_SpeedDown_Velocidad {
            get {
                return ResourceManager.GetString("Model_SpeedDown_Velocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Model_SpeedUp_Velocidad1 {
            get {
                return ResourceManager.GetString("Model_SpeedUp_Velocidad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Inactivo.
        /// </summary>
        public static string Model_TicketInactive {
            get {
                return ResourceManager.GetString("Model_TicketInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Refrescar.
        /// </summary>
        public static string Model_TicketRefresh {
            get {
                return ResourceManager.GetString("Model_TicketRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Ticket.
        /// </summary>
        public static string Model_TicketTime_Tiempo {
            get {
                return ResourceManager.GetString("Model_TicketTime_Tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un Registro con el mismo Valor.
        /// </summary>
        public static string Msg_DoubleData {
            get {
                return ResourceManager.GetString("Msg_DoubleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar un Item.
        /// </summary>
        public static string Msg_Range {
            get {
                return ResourceManager.GetString("Msg_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registo no puede ser Eliminado, porque tiene relacion con otros Datos.
        /// </summary>
        public static string Msg_Relationship {
            get {
                return ResourceManager.GetString("Msg_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Eliminar este Registro?.
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Ticket WIFI para Mikrotik.
        /// </summary>
        public static string NombreSoftware {
            get {
                return ResourceManager.GetString("NombreSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string OderTiket_Model_Precio {
            get {
                return ResourceManager.GetString("OderTiket_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tickets.
        /// </summary>
        public static string OrderTicket_Index_Titulo {
            get {
                return ResourceManager.GetString("OrderTicket_Index_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string OrderTicket_Model_Cantidad {
            get {
                return ResourceManager.GetString("OrderTicket_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creados.
        /// </summary>
        public static string OrderTicket_Model_Creados {
            get {
                return ResourceManager.GetString("OrderTicket_Model_Creados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string OrderTicket_Model_Date {
            get {
                return ResourceManager.GetString("OrderTicket_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrotik.
        /// </summary>
        public static string OrderTicket_Model_Mikrotik {
            get {
                return ResourceManager.GetString("OrderTicket_Model_Mikrotik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden #.
        /// </summary>
        public static string OrderTicket_Model_OrdenNumero {
            get {
                return ResourceManager.GetString("OrderTicket_Model_OrdenNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Ticket.
        /// </summary>
        public static string OrderTicket_Model_PlanTicketId {
            get {
                return ResourceManager.GetString("OrderTicket_Model_PlanTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor.
        /// </summary>
        public static string OrderTicket_Model_ServerId {
            get {
                return ResourceManager.GetString("OrderTicket_Model_ServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string OrderTicket_Model_Total {
            get {
                return ResourceManager.GetString("OrderTicket_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        public static string OrderTicketDetail_Model_Clave {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Servidor.
        /// </summary>
        public static string OrderTicketDetail_Model_IpServer {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_IpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrotik ID.
        /// </summary>
        public static string OrderTicketDetail_Model_MikrotikID {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_MikrotikID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden Ticket.
        /// </summary>
        public static string OrderTicketDetail_Model_OrdenTicket {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_OrdenTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string OrderTicketDetail_Model_PlanTicketId {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_PlanTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string OrderTicketDetail_Model_TicketNumero {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_TicketNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string OrderTicketDetail_Model_Usuario {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad.
        /// </summary>
        public static string OrderTicketDetail_Model_Velocidad {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_Velocidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendido.
        /// </summary>
        public static string OrderTicketDetail_Model_Vendido {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_Vendido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajero.
        /// </summary>
        public static string OrderTicketDetail_Model_VendidoCajero {
            get {
                return ResourceManager.GetString("OrderTicketDetail_Model_VendidoCajero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Vendidos.
        /// </summary>
        public static string OrderTickets_Reporte {
            get {
                return ResourceManager.GetString("OrderTickets_Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string PirntView_Model_DateEnd {
            get {
                return ResourceManager.GetString("PirntView_Model_DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string PlanCategory_Model_Categoria {
            get {
                return ResourceManager.GetString("PlanCategory_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Transparente.
        /// </summary>
        public static string PlanCategory_Model_TransparentProxy {
            get {
                return ResourceManager.GetString("PlanCategory_Model_TransparentProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Planes.
        /// </summary>
        public static string PlanCategory_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("PlanCategory_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string PlanCateogry_Model_Detail {
            get {
                return ResourceManager.GetString("PlanCateogry_Model_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string PlanTicket_Model_Detalle {
            get {
                return ResourceManager.GetString("PlanTicket_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string PlanTicket_Model_Impuesto {
            get {
                return ResourceManager.GetString("PlanTicket_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac Cookies.
        /// </summary>
        public static string PlanTicket_Model_macCookies {
            get {
                return ResourceManager.GetString("PlanTicket_Model_macCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string PlanTicket_Model_Plan {
            get {
                return ResourceManager.GetString("PlanTicket_Model_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string PlanTicket_Model_Precio {
            get {
                return ResourceManager.GetString("PlanTicket_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Transparente.
        /// </summary>
        public static string PlanTicket_Model_Proxy {
            get {
                return ResourceManager.GetString("PlanTicket_Model_Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip Servidor.
        /// </summary>
        public static string PlanTicket_Model_Server {
            get {
                return ResourceManager.GetString("PlanTicket_Model_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        public static string PlanTicket_Model_ShareUser {
            get {
                return ResourceManager.GetString("PlanTicket_Model_ShareUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string PlanTicket_Model_SpeedDown {
            get {
                return ResourceManager.GetString("PlanTicket_Model_SpeedDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string PlanTicket_Model_SpeedUp {
            get {
                return ResourceManager.GetString("PlanTicket_Model_SpeedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo/Inactivo.
        /// </summary>
        public static string PlanTicket_Model_TicketInactive {
            get {
                return ResourceManager.GetString("PlanTicket_Model_TicketInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo/Refresh.
        /// </summary>
        public static string PlanTicket_Model_TicketRefresh {
            get {
                return ResourceManager.GetString("PlanTicket_Model_TicketRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo/Plan.
        /// </summary>
        public static string PlanTicket_Model_TicketTime {
            get {
                return ResourceManager.GetString("PlanTicket_Model_TicketTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Tickets.
        /// </summary>
        public static string PlanTicket_Model_Titulo {
            get {
                return ResourceManager.GetString("PlanTicket_Model_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikrotik Id.
        /// </summary>
        public static string PlanTicket_Modelo_Mikrotik {
            get {
                return ResourceManager.GetString("PlanTicket_Modelo_Mikrotik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subida / Bajada.
        /// </summary>
        public static string PlanTicket_Modelo_upDown {
            get {
                return ResourceManager.GetString("PlanTicket_Modelo_upDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo.
        /// </summary>
        public static string Print_Codigo {
            get {
                return ResourceManager.GetString("Print_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Print_Plan {
            get {
                return ResourceManager.GetString("Print_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket #.
        /// </summary>
        public static string Print_Ticket {
            get {
                return ResourceManager.GetString("Print_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string PrintView_Model_Company {
            get {
                return ResourceManager.GetString("PrintView_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string PrintView_Model_DateStar {
            get {
                return ResourceManager.GetString("PrintView_Model_DateStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cajero.
        /// </summary>
        public static string PrinView_Model_Cachier {
            get {
                return ResourceManager.GetString("PrinView_Model_Cachier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden Tickets.
        /// </summary>
        public static string Register_Model_OrderTickets {
            get {
                return ResourceManager.GetString("Register_Model_OrderTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Register_Model_Tickets {
            get {
                return ResourceManager.GetString("Register_Model_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Cajero.
        /// </summary>
        public static string Register_Model_VentaCachier {
            get {
                return ResourceManager.GetString("Register_Model_VentaCachier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta#.
        /// </summary>
        public static string Register_Model_VentaOne {
            get {
                return ResourceManager.GetString("Register_Model_VentaOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo.
        /// </summary>
        public static string Register_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Register_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} es Requerido.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despacho Tickets.
        /// </summary>
        public static string SellTicket_Model_Despacho {
            get {
                return ResourceManager.GetString("SellTicket_Model_Despacho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string SellTicket_Model_Ticket {
            get {
                return ResourceManager.GetString("SellTicket_Model_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Ticket.
        /// </summary>
        public static string SellTicket_Model_Titulo {
            get {
                return ResourceManager.GetString("SellTicket_Model_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta Tickets por Cajero.
        /// </summary>
        public static string SellTicketCachier_Titulo {
            get {
                return ResourceManager.GetString("SellTicketCachier_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidores.
        /// </summary>
        public static string Server_Index_Titulo {
            get {
                return ResourceManager.GetString("Server_Index_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        public static string Server_Model_Clave {
            get {
                return ResourceManager.GetString("Server_Model_Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Server_Model_Detalle {
            get {
                return ResourceManager.GetString("Server_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Servidor.
        /// </summary>
        public static string Server_Model_IpServidor {
            get {
                return ResourceManager.GetString("Server_Model_IpServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string Server_Model_Modelo {
            get {
                return ResourceManager.GetString("Server_Model_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Servidor.
        /// </summary>
        public static string Server_Model_Nombre {
            get {
                return ResourceManager.GetString("Server_Model_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Server_Model_Usuario {
            get {
                return ResourceManager.GetString("Server_Model_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string SpeedDown_Titulo {
            get {
                return ResourceManager.GetString("SpeedDown_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpLoad.
        /// </summary>
        public static string SpeedUp_Titualo {
            get {
                return ResourceManager.GetString("SpeedUp_Titualo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_Model_Impuesto {
            get {
                return ResourceManager.GetString("Tax_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL Valor del {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string Tax_Model_RangeMsg {
            get {
                return ResourceManager.GetString("Tax_Model_RangeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string Tax_Model_Tasa {
            get {
                return ResourceManager.GetString("Tax_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_ViewIndex_Titulo {
            get {
                return ResourceManager.GetString("Tax_ViewIndex_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Sistema/Texto Encabezado, podra cambiar por la direccion, telefono y correo.
        /// </summary>
        public static string TextHead_Default {
            get {
                return ResourceManager.GetString("TextHead_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string TextHead_Model_TextEncabezado {
            get {
                return ResourceManager.GetString("TextHead_Model_TextEncabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string TextHead_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("TextHead_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Ticket.
        /// </summary>
        public static string TicketTime_Titulo {
            get {
                return ResourceManager.GetString("TicketTime_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string User_Model_Address {
            get {
                return ResourceManager.GetString("User_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave PC.
        /// </summary>
        public static string User_Model_ClavePc {
            get {
                return ResourceManager.GetString("User_Model_ClavePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string User_Model_Company {
            get {
                return ResourceManager.GetString("User_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string User_Model_Email {
            get {
                return ResourceManager.GetString("User_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FisrtName {
            get {
                return ResourceManager.GetString("User_Model_FisrtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FullName {
            get {
                return ResourceManager.GetString("User_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string User_Model_LastName {
            get {
                return ResourceManager.GetString("User_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string User_Model_Phone {
            get {
                return ResourceManager.GetString("User_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string User_Model_Photo {
            get {
                return ResourceManager.GetString("User_Model_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string User_Model_Puesto {
            get {
                return ResourceManager.GetString("User_Model_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("User_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string VentaTicket_Creacion {
            get {
                return ResourceManager.GetString("VentaTicket_Creacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venta.
        /// </summary>
        public static string VentaTicket_Venta {
            get {
                return ResourceManager.GetString("VentaTicket_Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ViewCreate {
            get {
                return ResourceManager.GetString("ViewCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ViewDelete {
            get {
                return ResourceManager.GetString("ViewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ViewEdit {
            get {
                return ResourceManager.GetString("ViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zone_Model_Zone {
            get {
                return ResourceManager.GetString("Zone_Model_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Zone_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Zone_ViewIndex_Titulo1", resourceCulture);
            }
        }
    }
}
